---
title: "HahnBaadenLaurent_EarthObservationMAP"
output: html_document
---

## Setup
```{r}
## load necessary packages
pck_list <- c("assertthat","tidyverse", "e1071", "viridisLite", "terra", "randomForest", "sf",)
lapply(pck_list, require, character.only = TRUE)
rm(pck_list)

knitr::opts_knit$set(root.dir = "~/earthobservation-map")

```
## Exploring STMs
```{r}
# load stms
tcg <- rast("~/00_map_data/data/Sentinel-2/TSI_MZQ-CABO-DELGADO_2019-2023_SEN2_TCG.tif")
tcb <- rast("~/00_map_data/data/Sentinel-2/TSI_MZQ-CABO-DELGADO_2019-2023_SEN2_TCB.tif")
tcw <- rast("~/00_map_data/data/Sentinel-2/TSI_MZQ-CABO-DELGADO_2019-2023_SEN2_TCW.tif")

# load country vectos
mz_geojson <- vect("~/00_map_data/data/mz.json")
mz_shp <- vect("~/00_map_data/moz_admbnda_adm0_ine_20190607.shp")

```
## Conducting Accuracy Assessment
```{r}
### For more information regarding each raster, please see 
### readme file and research article


# load global cropland extent (potapov)
potapov <- rast("~/00_map_data/data/Potapov-etal-2021_global-cropland/Potapov-etal-2021_global-cropland_2019.tif")

# load xxx national-level extent()
national_level <- rast("~/00_map_data/data/Mozambique_cropland_10m_2017_2019.tif")

# crop national-level raster
national_level <- st_crop(national_level, mz_shp)
```

## Accuracy Assessment
```{r}
# 
```