---
title: "HahnBaadenLaurent_EarthObservationMAP"
output: html_document
---

## Setup
```{r}
## load necessary packages
pck_list <- c("assertthat","tidyverse", "e1071", "viridisLite", "terra", "randomForest", "sf", "tidyterra")
lapply(pck_list, require, character.only = TRUE)
rm(pck_list)

knitr::opts_knit$set(root.dir = "~/earthobservation-map")

```

## Exploring STMs
```{r}
# load tassled cap transformations: greenness, brightness, and wetness
tcg <- rast("~/00_map_data/data/Sentinel-2/TSI_MZQ-CABO-DELGADO_2019-2023_SEN2_TCG.tif")
tcb <- rast("~/00_map_data/data/Sentinel-2/TSI_MZQ-CABO-DELGADO_2019-2023_SEN2_TCB.tif")
tcw <- rast("~/00_map_data/data/Sentinel-2/TSI_MZQ-CABO-DELGADO_2019-2023_SEN2_TCW.tif")

# stack tcts
tct <- c(tcb, tcg, tcw)

# inspect tct band names
tct_names <- names(tct)

## FILTER BANDS BY GROWING SEASON 2020/2021
## AUTHORS: SIMON HAHN & MORITZ BAADEN

# create function
subset_by_season <- function(rast,
                             start_date,
                             end_date,
                             prefix = "TCW_")
{
  start_date <- as.Date(start_date)
  end_date <- as.Date(end_date)
  
  all_names <- names(rast)
  layer_dates <- as.Date(sub(prefix, "", all_names), format = 
                           "%Y%m%d")
  
  idx <- which(layer_dates >= start_date & layer_dates <= end_date)
  
  rast[[idx]]
}

# subset raster stack for 2020/2021 growing season
tct_20.21 <- subset_by_season(tct, 
                              start_date = "2020-09-19",
                              end_date = "2021-08-25")

```

```{r}
# load training data
training_path <- "~/00_map_data/data/cropland_init.gpkg"

# read training data
train_pts <- st_read(training_path)

# reproject training pts
train_pts <- st_transform(train_pts, crs(tct_20.21))

# extract raster values
train_vect <- vect(train_pts)
extracted <- terra::extract(tct_20.21, train_vect)

# create tibble of extract data
training_data <- as_tibble(extracted, name_repair = T)

# combine with class, 
if ("ID" %in% names(training_data)) training_data <- training_data %>% select(-ID)
training_data <- training_data %>% 
  mutate(class = factor(train_pts$class, levels = c(1,2), labels = c("cropland","noncropland")))

# remove rows w/ na obs
training_data_clean <- training_data %>%
  drop_na()
```

```{r}
## TRAIN RANDOM FOREST MODEL
# remove coordinate columns
predictor_cols <- setdiff(names(training_data_clean), "class")
cat("Predictor variables used: ", paste(predictor_cols, collapse = ", "), "\n")

set.seed(123)

rf_model <- randomForest(x = training_data_clean %>% select(all_of(predictor_cols)),
                         y = training_data_clean$class,
                         ntree = 500,
                         importance = TRUE)
print(rf_model)
# Variable importance
var_imp <- importance(rf_model)
print(var_imp)
# Optional: plot variable importance
# varImpPlot(rf_model)
```

```{r}
cat("Predicting classification map for 2021...\n")
prediction_map <- predict(tc_all_20.21, rf_model, type = "prob", filename = "~/EarthObservation/Project/Results/prediction_tc_all_20-21.tif", overwrite = TRUE)
cat("Saved prediction raster to '~/EarthObservation/Results/prediction_all_2021.tif'\n")
plot(prediction_map)
```

```{r}
# load country vectors
mz_geojson <- vect("~/00_map_data/data/mz.json")
mz_shp <- vect("~/00_map_data/moz_admbnda_adm0_ine_20190607.shp")

```
## Conducting Accuracy Assessment
```{r}
### For more information regarding each raster, please see 
### readme file and research article


# load global cropland extent (potapov et al)
potapov <- rast("~/00_map_data/data/Potapov-etal-2021_global-cropland/Potapov-etal-2021_global-cropland_2019.tif")

# load comparison binary cropland (bofana et al)
national_level <- rast("~/00_map_data/data/Mozambique_cropland_10m_2017_2019.tif")

```

```{r}
# load probability stack
prob_stack <- rast("~/00_map_data/data/probabilities_tc_all_20-21.tif")

# extract band
cropland_band <- prob_stack[[1]] > 0.3 & prob_stack[[1]] < 0.7
noncropland_band <- prob_stack[[2]] > 0.3 & prob_stack[[1]] < 0.7

# build conditions for both bands


prob.filtered <- mask(prob_stack, condition)

writeRaster(prob.filtered, "~/00_map_data/data/filtered_prob.tif", overwrite = T)
```

```{r}
# subset national-level raster
national_level_crop <- terra::crop(national_level, mz_shp)
national_level_final <- terra::mask(national_level_crop, mz_shp)
writera
```
